### PR TITLE
fix(nix-health): use `direnv status --json` & create `direnv` crate

### LINKED ISSUE #122: `nix-health`: `direnv allow` check failure
Screenshot 2024-03-19 at 12 15 41 AM

The check above fails even though `direnv allow` has been run:
Screenshot 2024-03-19 at 12 15 54 AM

Here 0 means `Allowed`, for explanation, see: https://github.com/direnv/direnv/pull/1142#issuecomment-1848677532

### PR DESCRIPTION
**Pull request by shivaraj-bh**
resolves #122 

* fix the broken activation (`direnv allow`) check

### CODE REVIEW

File: crates/nix_health/src/check/direnv.rs [hunk 1]
```diff
@@ -93,71 +93,74 @@ fn activation_check(local_flake: &std::path::Path, required: bool) -> Check {
...
 
-impl DirenvInstall {
-    /// Detect user's direnv installation
+#[derive(Debug, Serialize, Deserialize, Clone)]
+struct DirenvConfig {
+    #[serde(rename = "ConfigDir")]
+    config_dir: PathBuf,
+    /// Path to the direnv binary
+    #[serde(rename = "SelfPath")]
+    self_path: PathBuf,
```
Comment (shivaraj-bh) [inline crates/nix_health/src/check/direnv.rs:126]: This will be useful to also solve #120

File: crates/nix_health/src/check/direnv.rs [hunk 2]
```diff
@@ -93,71 +93,74 @@ fn activation_check(local_flake: &std::path::Path, required: bool) -> Check {
...
+fn is_direnv_allowed_on(project_dir: &std::path::Path) -> anyhow::Result<bool> {
+    let output = std::process::Command::new("direnv")
+        .args(["status", "--json"])
+        .current_dir(project_dir)
+        .output()?;
+    if output.status.success() {
+        let out = String::from_utf8_lossy(&output.stdout);
+        let status = DirenvStatus::from_json(&out)?;
+        // rc.allowed == 0 means that the .envrc is allowed, see: https://github.com/direnv/direnv/pull/1142#issuecomment-1848677532
+        Ok(status.state.found_rc.map_or(false, |rc| rc.allowed == 0))
```
Comment (srid) [inline crates/nix_health/src/check/direnv.rs:107]: You can move this to a method on the struct, viz.:

```rust
impl DirenvStatus {
  fn is_allowed(self) -> bool { ... }
}
```

This way the caller doesn't have to care about the implementation; only the semantics.

Comment (srid) [reply crates/nix_health/src/check/direnv.rs:107]: Actually it should be on `DirenvState`

File: crates/nix_health/src/check/direnv.rs [hunk 3]
```diff
@@ -93,71 +93,74 @@ fn activation_check(local_flake: &std::path::Path, required: bool) -> Check {
...
-    pub bin_path: PathBuf,
+/// [Check] if direnv was already allowed in [project_dir]
 
-    /// Contents of `direnvrc`
-    pub direnv_config: Option<String>,
+fn is_direnv_allowed_on(project_dir: &std::path::Path) -> anyhow::Result<bool> {
+    let output = std::process::Command::new("direnv")
+        .args(["status", "--json"])
+        .current_dir(project_dir)
+        .output()?;
```
Comment (shivaraj-bh) [inline crates/nix_health/src/check/direnv.rs:102]: `direnv status —json` is only possible from direnv >= 2.33.0, so older versions will not be supported.

I am wondering if it would be better to introduce a `version_check`

File: crates/nix_health/src/check/direnv.rs [hunk 4]
```diff
@@ -93,71 +93,74 @@ fn activation_check(local_flake: &std::path::Path, required: bool) -> Check {
...
+    config: DirenvConfig,
+    state: DirenvState,
 }
 
-impl DirenvInstall {
-    /// Detect user's direnv installation
+#[derive(Debug, Serialize, Deserialize, Clone)]
+struct DirenvConfig {
+    #[serde(rename = "ConfigDir")]
+    config_dir: PathBuf,
```
Comment (srid) [inline crates/nix_health/src/check/direnv.rs:123]: Could you add a `///` description here? What is this directory?

File: crates/nix_health/src/check/direnv.rs (hunk 3 above)
Comment (srid) [reply crates/nix_health/src/check/direnv.rs:102]: If it doesn't affect our internal projects like Euler, we could just drop support for old direnv to keep the code simple.

Comment (srid) [reply crates/nix_health/src/check/direnv.rs:102]: But yes in that case, a version check is probably still useful, so we can tell the user (as red/orange message) in that case that their direnv version is too old.

Comment (shivaraj-bh) [reply crates/nix_health/src/check/direnv.rs:102]: The file might get rather long if I have to create another struct for version. It won’t if I use the semver crate and let it parse the version.

Comment (srid) [reply crates/nix_health/src/check/direnv.rs:102]: Better to reuse external crate when possible. 

https://docs.rs/semver/1.0.22/semver/

I wonder why we didn't use it here:

https://github.com/juspay/nix-browser/blob/358f3c444918bc4a577e7e06341173c40e0038e1/crates/nix_rs/src/version.rs#L11-L15

**Comment by shivaraj-bh** [comment]
Here’s a handy screen grab for what it looks like currently:
Screenshot 2024-03-20 at 12 09 36 AM

File: crates/nix_health/src/check/direnv.rs [hunk 5]
```diff
@@ -71,14 +80,45 @@ fn install_check(required: bool) -> Check {
...
+                suggestion,
+            },
+            Ok(None) => CheckResult::Red {
+                msg: "Unable to parse direnv version".to_string(),
+                suggestion,
+            },
+            Err(e) => CheckResult::Red {
+                msg: format!("Unable to locate direnv: {}", e),
+                suggestion,
+            },
```
Comment (srid) [inline crates/nix_health/src/check/direnv.rs:108]: Shouldln't "Direnv Installation" check happen *before* the version check? Then this clause becomes obviated.

File: crates/nix_health/src/check/direnv.rs [hunk 6]
```diff
@@ -93,71 +133,99 @@ fn activation_check(local_flake: &std::path::Path, required: bool) -> Check {
...
+    #[serde(rename = "foundRC")]
+    found_rc: Option<DirenvRC>,
+    /// Information about the .envrc that is currently allowed using `direnv allow`
+    #[serde(rename = "loadedRC")]
+    loaded_rc: Option<DirenvRC>,
+}
+
+impl DirenvState {
+    /// Check if the .envrc file is allowed
+    fn is_found_rc_allowed(&self) -> bool {
```
Comment (srid) [inline crates/nix_health/src/check/direnv.rs:194]:
```suggestion
    fn is_allowed(&self) -> bool {
```

Why? Because function name should reflect semantics not implementation.

File: crates/nix_health/src/check/direnv.rs [hunk 7]
```diff
@@ -93,71 +133,99 @@ fn activation_check(local_flake: &std::path::Path, required: bool) -> Check {
...
+        Ok(status.state.is_found_rc_allowed())
+    } else {
+        anyhow::bail!("Unable to run direnv status --json: {:?}", output.stderr)
     }
 }
 
-/// Check if direnv was already activated in [project_dir]
-
-pub fn is_direnv_active_on(project_dir: &std::path::Path) -> anyhow::Result<bool> {
+fn direnv_version() -> anyhow::Result<String> {
```
Comment (srid) [inline crates/nix_health/src/check/direnv.rs:152]: I think this should return `Semver` instead of `String`. 

Function interface should be as smaller as possible.

**Comment by shivaraj-bh** [comment]
Much better!
Screenshot 2024-03-20 at 12 29 57 AM

File: crates/nix_health/src/check/direnv.rs [hunk 8]
```diff
@@ -93,71 +133,99 @@ fn activation_check(local_flake: &std::path::Path, required: bool) -> Check {
...
-impl DirenvInstall {
-    /// Detect user's direnv installation
+/// [Check] if direnv was already allowed in [project_dir]
 
-    pub fn detect() -> anyhow::Result<Self> {
-        let bin_path = which::which("direnv")?;
-        let output = std::process::Command::new(&bin_path)
-            .arg("status")
-            .output()?;
+fn is_direnv_allowed_on(project_dir: &std::path::Path) -> anyhow::Result<bool> {
```
Comment (srid) [inline crates/nix_health/src/check/direnv.rs:140]: This can be moved as a method of `DirenvInstall` struct, no? This way we can run direnv using the exact detected path (`bin_path`) instead of searching $PATH again.

File: crates/nix_health/src/check/direnv.rs (hunk 7 above)
Comment (srid) [reply crates/nix_health/src/check/direnv.rs:154]: Likewise, this should probably be a method of `DirenvInstall`.

File: crates/nix_health/src/check/direnv.rs [hunk 9]
```diff
@@ -31,17 +33,33 @@ impl Checkable for Direnv {
...
+        let direnv_install_check = install_check(&direnv_install, self.required);
         let direnv_installed = direnv_install_check.result.green();
         checks.push(direnv_install_check);
 
-        if direnv_installed {
+        if !direnv_installed {
+            return checks;
+        }
+
+        let direnv_version = version_check(direnv_install.as_ref().unwrap());
```
Comment (shivaraj-bh) [inline crates/nix_health/src/check/direnv.rs:46]: After moving `direnv_version` and `is_direnv_allowed_on` to impl of `DirenvInstall`, I am passing the `direnv_install` object around, that doesn’t look nice.

Comment (srid) [reply crates/nix_health/src/check/direnv.rs:46]: > I am passing the direnv_install object around, that doesn’t look nice.

That is not a problem in and of itself (structs are meant to be passed around anyway), unless you are referring to something else - such as the resulting code being complex.

I'll take a look, in a bit.

Comment (srid) [reply crates/nix_health/src/check/direnv.rs]: > that doesn’t look nice.

I think you are mostly referring to the parts where I added TODO/FIXME in the code. But I want to improve the various `*_check` functions as well.

**Review by srid — APPROVED** [review]

**Comment by srid** [comment]
https://crates.io/crates/direnv
